name: Generate Snake Game

on:
  schedule:
    - cron: "0 */6 * * *" # Every 6 hours
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jayehernandez/jayehernandez@latest
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: Adishiv9494
